spring:
  datasource:
    username: nani
    password: nani
    url: jdbc:mysql://localhost:3306/IES
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: REST-API
        
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  mail:
    username: vineethyadavnaluvala023@gmail.com
    password: bmkmuguhxsulpdel
    
    host: smtp.gmail.com
    port: 587
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8087
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  